### ISSUE TITLE
Reference base at hg38 position error mechanism.

### ISSUE THREAD

**Issue by tkmamidi** [uab-cgds-worthey/DITTO-UI#12]
Reference base at hg38 position `1:2406478` is `C`. However when I input the reference as `A`, instead of displaying an error message, the webapp returns an output with ditto scores. Please check the error mechanism.

_Originally posted by @ManavalanG in https://github.com/uab-cgds-worthey/DITTO-UI/issues/11#issuecomment-1832108288_

**Comment by ManavalanG** [comment]
Great to see the feature addition to verify the reference nucleotide. I would recommend improving the verification status message to something like this:

```
    if ref != query_variant(str(chrom), int(pos)):
        st.warning(f"Provided reference nucleotide {user_ref} doesn't match the actual nucleotide {actual_ref} . Please fix the input and try again.")
    #else:
       # st.success("Reference nucleotide matches the reference genome.")
```

I commented out success message as it is not relevant to the user; only the failure is.

**Comment by tkmamidi** [comment]
Taken care in #11
